project:
  type: website
  output-dir: docs

website:
  title: "PSYCH Graduate Statistics Assignment"

format:
  html:
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    embed-resources: true
    theme: cosmo